In [1]:
import numpy as np

In [28]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
import numpy as np
import pandas as pd

In [35]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [36]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [37]:
pd.Series(data = my_data,index = labels)

a    10
b    20
c    30
dtype: int64

In [38]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [40]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [41]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [43]:
my_data

[10, 20, 30]

In [44]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [45]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [46]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])

In [47]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [48]:
ser1['USA']

1

In [49]:
from numpy.random import randn

In [50]:
np.random.seed(101)

In [51]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [52]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [53]:
type(df['W'])

pandas.core.series.Series

In [54]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [55]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [56]:
df['new'] = df['W'] + df['Y']

In [57]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [60]:
df.drop('new',axis=1,inplace=True)

In [65]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [67]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [68]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [69]:
df.shape

(5, 4)

In [70]:
df[['Z','X']]

Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [71]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [72]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [73]:
df.loc['B','Y']

-0.8480769834036315

In [74]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077